export const TASK_SERVICE_RABBITMQ = "TASK_SERVICE_RABBITMQ";
export const AUTH_SERVICE_TCP = "AUTH_SERVICE_TCP";
export const USER_SERVICE_RABBITMQ = "USER_SERVICE_RABBITMQ";
export const NOTIFICATION_SERVICE_RABBITMQ = "NOTIFICATION_SERVICE_RABBITMQ";

export const USER_SERVICE = "USER_SERVICE";
